apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  annotations:
    kubernetes.io/ingress.class: ingress-controller-internal-nginx
    nginx.ingress.kubernetes.io/default-backend: argocd-server
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: argocd
spec:
  rules:
    - host: argocd.eu-west-1.dev.nexmo.vip
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: argocd-server
              servicePort: http
