apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: atlantis-vcs
spec:
  backendType: secretsManager
  data:
    - key: atlantis_aws_credentials
      name: aws-credentials

---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-token
  namespace: atlantis-vcs
spec:
  backendType: secretsManager
  data:
    - key: atlantis_github_token
      name: github-token

---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: webhook-secret
  namespace: atlantis-vcs
spec:
  backendType: secretsManager
  data:
    - key: atlantis_webhook_secret
      name: webhook-secret

---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: healthchecksio-apitoken
  namespace: atlantis-vcs
spec:
  backendType: secretsManager
  data:
    - key: atlantis_healthchecksio_apitoken
      name: healthchecksio-apitoken

---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ldap-tls-ca-cert
  namespace: atlantis-vcs
spec:
  backendType: secretsManager
  region: eu-west-1
  data:
    - key: global/sre/other/atlantis_ldap_tls_ca_cert
      name: ldap-tls-ca-cert

---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ldap-bind-password
  namespace: atlantis-vcs
spec:
  backendType: secretsManager
  region: eu-west-1
  data:
    - key: global/sre/other/atlantis_ldap_bind_password
      name: ldap-bind-password
