# public github webhook ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atlantis-webhook-ingress
  annotations:
    kubernetes.io/ingress.class: ingress-controller-public-nginx
    nginx.ingress.kubernetes.io/default-backend: atlantis
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /events
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  namespace: atlantis-vcs
spec:
  rules:
    - host: gh-webhook.nexmo.cloud
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: atlantis
              servicePort: atlantis
