apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "ingress-controller-internal-nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: argocd-server
              servicePort: http
      host: argocd.eu-west-2.nexmo.vip
  tls:
    - hosts:
        - argocd.eu-west-2.nexmo.vip
      secretName: argocd-secret # do not change, this is provided by Argo CD
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-grpc-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "ingress-controller-internal-nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: argocd-server
              servicePort: https
      host: grpc.argocd.eu-west-2.nexmo.vip
  tls:
    - hosts:
        - grpc.argocd.eu-west-2.nexmo.vip
      secretName: argocd-secret # do not change, this is provided by Argo CD
